server:
 port: 9527
spring:
 application:
  name: microservicecloud-zuul-gateway
eureka:
 client:
  service-url:
   defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
 instance:
  instance-id: gateway-9527
  prefer-ip-address: true
info:
 app.name: atguigu-microcloud
 company.name: www.atguigu.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$

#beforehttp://localhost:9527/microservicecloud-dept/dept/get/2
#afterhttp://localhost:9527/mydept/dept/get/2
#配置路由
zuul:
 prefix: /atguigu
 ignored-services: "*"
 routes:
  mydept.serviceId: microservicecloud-dept
  mydept.path: /mydept/**